"""
Django settings for lotushair project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TESTING = "test" in sys.argv


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-19k&%jv45$0fgbvb0rp9+#8klfni63pir=q=l8*yln45k8686@",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() in {"1", "true", "yes", "on"}

ALLOWED_HOSTS = os.environ.get(
    "DJANGO_ALLOWED_HOSTS",
    "www.lotushair.pythonanywhere.com,lotushair.pythonanywhere.com,127.0.0.1,localhost",
).split(",")


# Application definition

INSTALLED_APPS = [
    'core',
    'pwa',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lotushair.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lotushair.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 60,  # Temps en secondes avant de renvoyer "database is locked"
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Brazzaville'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if TESTING
            else "whitenoise.storage.CompressedStaticFilesStorage"
        ),
    },
}

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'staff_login'
LOGIN_REDIRECT_URL = 'staff_dashboard'
LOGOUT_REDIRECT_URL = 'login'
SESSION_COOKIE_AGE = 60 * 60 * 6
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

PWA_SERVICE_WORKER_PATH = BASE_DIR / 'core' / 'templates' / 'core' / 'service_worker.js'
PWA_APP_NAME = 'Lotus Hair'
PWA_APP_DESCRIPTION = 'Application de suivi de ristourne de perruques pour les membres, cycles, versements et choix de modeles.'
PWA_APP_THEME_COLOR = '#3E1B25'
PWA_APP_BACKGROUND_COLOR = '#FAF9F6'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_START_URL = '/'
PWA_APP_ORIENTATION = 'portrait-primary'
PWA_APP_STATUS_BAR_COLOR = 'black-translucent'
PWA_APP_LANG = 'fr'
PWA_APP_ICONS = [
    {
        'src': '/static/core/img/pwa-icon-192.png',
        'sizes': '192x192',
        'type': 'image/png',
        'purpose': 'any maskable',
    },
    {
        'src': '/static/core/img/pwa-icon-512.png',
        'sizes': '512x512',
        'type': 'image/png',
        'purpose': 'any maskable',
    },
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/core/img/pwa-icon-192.png',
        'sizes': '192x192',
    },
]
PWA_APP_SHORTCUTS = [
    {
        'name': 'Tableau membre',
        'short_name': 'Tableau',
        'url': '/membre/',
        'description': 'Ouvrir le tableau membre',
        'icons': [{'src': '/static/core/img/pwa-icon-192.png', 'sizes': '192x192'}],
    },
    {
        'name': 'Catalogue',
        'short_name': 'Catalogue',
        'url': '/membre/catalogue/',
        'description': 'Ouvrir le catalogue',
        'icons': [{'src': '/static/core/img/pwa-icon-192.png', 'sizes': '192x192'}],
    },
]
PWA_APP_SPLASH_SCREEN = []

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
