# Generated by Django 5.1.2 on 2026-05-28 21:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='nom complet')),
                ('rank', models.PositiveIntegerField(verbose_name='rang')),
                ('code_hash', models.CharField(max_length=256, verbose_name='code chiffre')),
                ('status', models.CharField(default='actif', max_length=40, verbose_name='statut')),
                ('joined_at', models.DateField(default=django.utils.timezone.localdate, verbose_name="date d'inscription")),
                ('accepted_terms_at', models.DateTimeField(blank=True, null=True, verbose_name='conditions acceptees le')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'membre',
                'verbose_name_plural': 'membres',
                'ordering': ['group__name', 'rank', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='RistourneGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('cycle_days', models.PositiveIntegerField(default=15, verbose_name='duree du cycle')),
                ('contribution_amount', models.PositiveIntegerField(default=1250, verbose_name='montant de versement')),
                ('payment_frequency_days', models.PositiveIntegerField(default=1, verbose_name='rythme en jours')),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='debut du cycle')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'groupe',
                'verbose_name_plural': 'groupes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WigCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='nom du modele')),
                ('description', models.TextField(verbose_name='description')),
                ('image_url', models.URLField(blank=True, verbose_name='image')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'perruque',
                'verbose_name_plural': 'catalogue des perruques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='montant')),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='date de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirme'), ('late', 'En retard')], default='confirmed', max_length=20, verbose_name='statut')),
                ('note', models.CharField(blank=True, max_length=220, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.member')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.ristournegroup', verbose_name='groupe'),
        ),
        migrations.CreateModel(
            name='WigChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_final', models.BooleanField(default=False, verbose_name='choix final')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wig_choices', to='core.member')),
                ('wig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.wigcatalog')),
            ],
            options={
                'verbose_name': 'choix de perruque',
                'verbose_name_plural': 'choix de perruques',
                'ordering': ['-selected_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('group', 'rank')},
        ),
    ]
