# Generated by Django 5.1.2 on 2026-05-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wigcatalog',
            name='colors',
            field=models.CharField(blank=True, help_text='Separez les couleurs par des virgules.', max_length=255, verbose_name='couleurs disponibles'),
        ),
        migrations.AddField(
            model_name='wigcatalog',
            name='image',
            field=models.ImageField(blank=True, upload_to='catalogue/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='wigchoice',
            name='color',
            field=models.CharField(blank=True, max_length=80, verbose_name='couleur choisie'),
        ),
    ]
