# Generated by Django 5.1.2 on 2026-05-31 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wigcatalog_colors_wigcatalog_image_wigchoice_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='WigImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=80, verbose_name='couleur')),
                ('image', models.ImageField(upload_to='catalogue/couleurs/', verbose_name='image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.wigcatalog', verbose_name='modele')),
            ],
            options={
                'verbose_name': 'image de perruque',
                'verbose_name_plural': 'images de perruques',
                'ordering': ['wig__name', 'color', 'order', 'id'],
            },
        ),
    ]
