# Generated by Django 5.1.2 on 2026-05-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wigimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wigcatalog',
            name='sizes',
            field=models.CharField(blank=True, help_text='Separez les tailles par des virgules.', max_length=255, verbose_name='tailles disponibles'),
        ),
        migrations.AddField(
            model_name='wigchoice',
            name='size',
            field=models.CharField(blank=True, max_length=80, verbose_name='taille choisie'),
        ),
    ]
