# Generated by Django 5.1.2 on 2026-05-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_wigcatalog_sizes_wigchoice_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='derniere connexion'),
        ),
        migrations.AddField(
            model_name='member',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='derniere activite'),
        ),
    ]
