# Generated by Django 5.1.2 on 2026-06-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_member_last_login_at_member_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wigcatalog',
            name='visible_to_groups',
            field=models.ManyToManyField(blank=True, help_text='Laissez vide pour rendre ce modele visible a tous les groupes.', related_name='visible_wigs', to='core.ristournegroup', verbose_name='groupes autorises'),
        ),
    ]
