# Generated by Django 5.1.2 on 2026-06-02 12:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_wigcatalog_visible_to_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='montant')),
                ('withdrawn_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='date de retrait')),
                ('note', models.CharField(blank=True, max_length=220, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='core.ristournegroup', verbose_name='groupe')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='core.member', verbose_name='membre')),
            ],
            options={
                'verbose_name': 'retrait comptable',
                'verbose_name_plural': 'retraits comptables',
                'ordering': ['-withdrawn_on', '-created_at'],
            },
        ),
    ]
