# Generated by Django 5.1.2 on 2026-06-11 22:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_accountingwithdrawal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='titre')),
                ('message', models.TextField(verbose_name='message')),
                ('is_active', models.BooleanField(default=True, verbose_name='afficher')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible_to_groups', models.ManyToManyField(blank=True, help_text='Laissez vide pour ne pas limiter par groupe.', related_name='announcements', to='core.ristournegroup', verbose_name='groupes cibles')),
                ('visible_to_members', models.ManyToManyField(blank=True, help_text='Laissez vide pour ne pas limiter par membre.', related_name='announcements', to='core.member', verbose_name='membres cibles')),
            ],
            options={
                'verbose_name': 'annonce',
                'verbose_name_plural': 'annonces',
                'ordering': ['-created_at'],
            },
        ),
    ]
