# Generated by Django 5.1.2 on 2026-06-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_announcements', to='core.member', verbose_name='membres ayant lu'),
        ),
    ]
